auth_enabled: false

server:
  http_listen_port: 3100

frontend:
  address: 127.0.0.1
  max_outstanding_per_tenant: 2048
  compress_responses: true

frontend_worker:
  frontend_address: 127.0.0.1
  grpc_client_config:
    max_send_msg_size: 104857600
    max_recv_msg_size: 104857600

query_scheduler:
  max_outstanding_requests_per_tenant: 4096
  use_scheduler_ring: true

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m

limits_config:
  reject_old_samples: false
  reject_old_samples_max_age: 8760h  # 1 year
  max_cache_freshness_per_query: 10m

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    enabled: true
    dir: /loki/wal
  max_transfer_retries: 0
  max_chunk_age: 1h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s