services:

  app:
    image: ${DOCKER_IMAGE}
    ports:
      - "80:80"
    environment:
      - PORT=80
      - DB_PATH=/app/data/database.sqlite
      - ENVIRONMENT=production
      - GIN_MODE=release
    volumes:
      - type: bind
        source: /root/data/
        target: /app/data/
        consistency: consistent

    depends_on:
      - grafana
      - prometheus

  prometheus:
    image: prom/prometheus
    volumes:
        - type: bind
          source: /root/prometheus.yml
          target: /etc/prometheus/prometheus.yml
          consistency: consistent
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
