services:

  app:
    image: ${DOCKER_IMAGE}
    ports:
      - "80:80"
    environment:
      - PORT=80
      - ENVIRONMENT=production
      - GIN_MODE=release
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}

    depends_on:
      - grafana
      - prometheus

  prometheus:
    image: prom/prometheus
    volumes:
        - type: bind
          source: /root/prometheus.yml
          target: /etc/prometheus/prometheus.yml
          consistency: consistent
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
