services:

  app:
    image: ${DOCKER_IMAGE}

    ports:
      - "80:80"
    environment:
      - PORT=80
      - DB_PATH=/app/data/database.sqlite
      - ENVIRONMENT=production
    volumes:
      - type: bind
        source: /root/data/
        target: /app/data/
        consistency: consistent

    depends_on:
      - grafana
      - prometheus

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning  # Mount provisioning folder
      - grafana-data:/var/lib/grafana  # Persist Grafana data (dashboards, users, etc.)
    restart: always

volumes:
    grafana-data:  # Define the volume for Grafana data
    prometheus-data: