FROM golang:1.24

LABEL org.opencontainers.image.source = "https://github.com/devops-q/devops"

# Set destination for COPY
WORKDIR /app

# Install necessary dependencies for CGO
RUN apt-get update && apt-get install -y gcc

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build
RUN CGO_ENABLED=1 GOOS=linux go build -o ./create_api_user ./cmd/create_api_user/main.go

# Run
CMD ["./create_api_user"]